version: '3.7'

services:

  myfootball:
    container_name: "football-batch"
    image: postgres
    volumes:
      - football-batch:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

volumes:
  football-batch:
    driver: local