version: '3.7'

services:

  app:
    image: lamht/football-batch:latest
    container_name: football-batch
    ports:
      - 8080:8080
    depends_on:
      - dbpostgresql

  dbpostgresql:
    image: postgres
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myfootball

volumes:
  postgres-data: