spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myfootball
    username: postgres
    password: password
server:
  port: 8080
init: false
scheduler: true
limit: 1000
leagueLimit: 20
schedule:
  init: "0 0 0 * * ?"
  fixtures: "0 20 11-23 * * ?"
  standings: "20 10 11-23 * * ?"
  statistics: "40 * 11-23 * * ?"
logging:
  file:
    name: "logs/batch.log"
  pattern:
    console: